require 'net/http'
require 'uri'
require 'openai' # gem install ruby-openai


class OpenaiService
  def initialize(client)
    @client = client
  end
  
  def gen_topic(topic)
    response = @client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          { role: "system", content: "You are a helpful AI assistant that generates courses for our web application. In our learning from AI web application the user will enter a topic and you will provide the list of lessons in the course. Also please provide a description for each lesson, as well as a difficulty. Use the JSON schema: { name, lessons: [ {name, description, difficulty}, ... ]. Please use as many tokens as possible." },
          { role: "user", content: "Topic: #{topic}" },
        ],
        temperature: 0,
        max_tokens: 2000,
      }
    )
    
    puts response.choices[0].message['content']
    return response.choices[0].message['content']
  end

  def gen_lesson(name, description, difficulty)
    response = @client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          { role: "system", content: "You are a helpful AI assistant that generates great lessons as parts of a larger course generated by AI in our web application. Ensure that the lesson is robust and fully teaches the topic at hand. Format it in markdown. Thanks in advance." },
          { role: "user", content: "name=#{name}, description=#{description}, difficulty=#{difficulty}" },
        ],
        temperature: 0,
        max_tokens: 2000,
      }
    )
    
    puts response.choices[0].message['content']
    return response.choices[0].message['content']
  end
end

# Initialize the OpenAI client
client = OpenAI::Client.new(access_token: "sk_asdfasdf")

# Create an instance of the OpenaiService class with the client
openai_service = OpenaiService.new(client)
