version: "2.2"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_web1_development
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    # command: sleep 10000
      